name: lime
dependencies:
    - python=3.7
    - scikit-image=0.15.*
    - scikit-learn=0.21.*
    - pytorch=1.3.*
    - torchvision=0.4.*
    - pillow=6.2.*
    - numpy=1.17.*
    - pip:
        - progressbar=2.5

